import type {
  AnnualSeasonWindow,
  CountryPack,
  RegionPreviewHighlight,
} from "../types";

const SEED_SOURCE = "tripfit-dr-editorial-seed-v1";

function yearRound(reason: string): AnnualSeasonWindow[] {
  return [{ startMonth: 1, startDay: 1, endMonth: 12, endDay: 31, status: "AVAILABLE", reason }];
}

function highlight(
  value: Omit<RegionPreviewHighlight, "sourceIds" | "dataStatus" | "seasonWindows"> & {
    seasonWindows?: AnnualSeasonWindow[];
  },
): RegionPreviewHighlight {
  return {
    ...value,
    seasonWindows: value.seasonWindows ?? yearRound("Het hele jaar mogelijk; het dagweer bepaalt het beste moment."),
    sourceIds: [SEED_SOURCE],
    dataStatus: "SEED",
  };
}

export const dominicanRepublicPack: CountryPack = {
  country: {
    id: "do",
    name: "Dominicaanse Republiek",
    officialName: "Dominicaanse Republiek",
    slug: "dominicaanse-republiek",
    iso2Code: "DO",
    iso3Code: "DOM",
    defaultLocale: "nl-NL",
    languages: ["Spaans"],
    currencies: [{ code: "DOP", name: "Dominicaanse peso", symbol: "RD$" }],
    timeZones: ["America/Santo_Domingo"],
    center: { latitude: 18.7357, longitude: -70.1627 },
  },
  regions: [
    {
      id: "do-punta-cana",
      countryId: "do",
      name: "Punta Cana / Bávaro",
      slug: "punta-cana",
      aliases: ["Punta Cana", "Bávaro", "Cap Cana", "Uvero Alto", "Macao"],
      coverageLevel: "FLAGSHIP",
      center: { latitude: 18.582, longitude: -68.4055 },
      shortDescription: "Een toegankelijke oostkustbasis met lange stranden, excursies op zee en verrassende natuur landinwaarts.",
      context: {
        headline: "Meer dan een resortkust",
        identity: "Bávaro is levendig en praktisch, Cap Cana rustiger en verzorgd, terwijl Macao en het achterland een lokaler ritme hebben.",
        bestFor: ["stranddagen", "gezinnen", "wateractiviteiten", "comfortabele excursies"],
        gettingAround: "Afstanden tussen kustzones zijn groter dan ze op de kaart lijken; plan per dag één gebied en check transferduur.",
        seasonalNote: "December tot april is doorgaans droger. In de late zomer en herfst vragen hitte, buien en tropische systemen om flexibele buitenplannen.",
        localEtiquette: "Verlaat voor lokale eetadressen en Macao bewust de resortbubbel en vraag vooraf naar een betrouwbare terugrit.",
      },
      previewHighlights: [
        highlight({
          id: "pc-saona-early",
          title: "Vroege bootdag naar Saona",
          shortDescription: "Combineer een rustige start met natuur en strand, en voorkom waar mogelijk de drukste aankomstgolf.",
          kind: "SIGNATURE",
          interestIds: ["beach", "nature", "water-activities", "family-activities"],
          destinationClusterId: "do-pc-bavaro",
          priority: 96,
          familyFit: 84,
          minimumAge: 3,
          typicalDurationMinutes: 600,
          bookingAdvice: "Reserveer een kleinschalige aanbieder vooraf en controleer vertrekhaven, vaartijd en zwemvesten.",
          seasonWindows: [
            { startMonth: 6, endMonth: 11, status: "LIMITED", reason: "Vaker buien, hitte en kans op onrustiger zee; kies op korte termijn." },
            ...yearRound("Het hele jaar aangeboden; zeecondities blijven doorslaggevend."),
          ],
        }),
        highlight({
          id: "pc-playa-macao",
          title: "Playa Macao op het rustige dagdeel",
          shortDescription: "Een open, karaktervolle kust buiten de aaneengesloten resortstranden, het prettigst vóór hitte en drukte oplopen.",
          kind: "BEACH",
          interestIds: ["beach", "photography", "culture", "family-activities"],
          destinationClusterId: "do-pc-macao",
          priority: 90,
          familyFit: 74,
          typicalDurationMinutes: 240,
          seasonWindows: [
            { startMonth: 8, endMonth: 10, status: "LIMITED", reason: "Flexibel plannen rond tropische buien en branding." },
            ...yearRound("Jaarrond toegankelijk; branding en stroming verschillen per dag."),
          ],
        }),
        highlight({
          id: "pc-ojos-indigenas",
          title: "Ojos Indígenas natuurreservaat",
          shortDescription: "Een compact netwerk van bos en zoetwaterlagunes dat natuur toevoegt zonder een volledige transferdag.",
          kind: "NATURE",
          interestIds: ["nature", "family-activities", "photography", "wellness"],
          destinationClusterId: "do-pc-cap-cana",
          priority: 88,
          familyFit: 90,
          typicalDurationMinutes: 180,
        }),
        highlight({
          id: "pc-higuey-context",
          title: "Higüey: basiliek en lokaal stadsleven",
          shortDescription: "Plaats de toeristische oostkust in context met religieuze architectuur, marktstraten en het dagelijkse regionale centrum.",
          kind: "CULTURE",
          interestIds: ["culture", "history", "food", "photography"],
          destinationClusterId: "do-pc-higuey",
          priority: 82,
          familyFit: 78,
          typicalDurationMinutes: 240,
        }),
        highlight({
          id: "pc-bavaro-food",
          title: "Eetavond buiten het all-inclusive ritme",
          shortDescription: "Kies een compacte zone in Bávaro voor vis, criollo-gerechten of eigentijdse Dominicaanse keuken.",
          kind: "FOOD",
          interestIds: ["food", "culture", "nightlife", "family-activities"],
          destinationClusterId: "do-pc-bavaro",
          priority: 80,
          familyFit: 88,
          typicalDurationMinutes: 150,
          bookingAdvice: "Controleer dezelfde dag openingstijden en regel vooraf vervoer terug.",
        }),
        highlight({
          id: "pc-cotubanama",
          title: "Cotubanamá als natuuralternatief",
          shortDescription: "Grotten, kustbos en kalksteenlandschap maken van het zuidoosten meer dan alleen een strandtransfer.",
          kind: "NATURE",
          interestIds: ["nature", "history", "adventure", "photography"],
          destinationClusterId: "do-pc-bayahibe-gateway",
          priority: 84,
          familyFit: 68,
          minimumAge: 6,
          typicalDurationMinutes: 420,
        }),
      ],
    },
    {
      id: "do-santo-domingo",
      countryId: "do",
      name: "Santo Domingo",
      slug: "santo-domingo",
      aliases: ["Distrito Nacional", "Ciudad Colonial", "Zona Colonial"],
      coverageLevel: "FLAGSHIP",
      center: { latitude: 18.4861, longitude: -69.9312 },
      shortDescription: "De historische en hedendaagse hoofdstad: koloniale lagen, musea, muziek en een sterke eetcultuur dicht bij elkaar.",
      context: {
        headline: "Begin met context, niet met een checklist",
        identity: "Ciudad Colonial vertelt het vroeg-koloniale verhaal; daarbuiten toont de hoofdstad een moderne Caribische metropool met eigen ritmes en contrasten.",
        bestFor: ["geschiedenis", "cultuur", "eten", "architectuur", "stadse avonden"],
        gettingAround: "Verken Ciudad Colonial lopend, maar gebruik voor Los Tres Ojos en moderne wijken gericht vervoer en vermijd spitsuren.",
        seasonalNote: "Stadsbezoek werkt jaarrond. Plan wandelingen vroeg of laat op hete dagen en houd een museumoptie achter de hand bij stevige buien.",
        localEtiquette: "Kleding en tempo zijn verzorgd; vraag toestemming voor portretten en behandel religieuze locaties als actieve plekken, niet alleen als decor.",
      },
      previewHighlights: [
        highlight({
          id: "sd-colonial-story-walk",
          title: "Ciudad Colonial met verhaallijn",
          shortDescription: "Loop van machtscentrum naar woonstraten en rivierzijde, met aandacht voor zowel monumenten als de mensen achter de geschiedenis.",
          kind: "SIGNATURE",
          interestIds: ["history", "culture", "photography", "family-activities"],
          destinationClusterId: "do-sd-ciudad-colonial",
          priority: 98,
          familyFit: 86,
          typicalDurationMinutes: 210,
        }),
        highlight({
          id: "sd-tres-ojos",
          title: "Los Tres Ojos vóór de middaghitte",
          shortDescription: "Ondergrondse kalksteenmeren en korte wandelpaden vormen een sterke natuurpauze vlak buiten het centrum.",
          kind: "NATURE",
          interestIds: ["nature", "photography", "family-activities", "history"],
          destinationClusterId: "do-sd-east",
          priority: 91,
          familyFit: 86,
          minimumAge: 4,
          typicalDurationMinutes: 150,
        }),
        highlight({
          id: "sd-museums-rain-plan",
          title: "Koloniale musea als inhoudelijk regenplan",
          shortDescription: "Museo de las Casas Reales en omliggende collecties houden de historische lijn sterk wanneer buiten minder aantrekkelijk is.",
          kind: "CULTURE",
          interestIds: ["history", "culture", "family-activities"],
          destinationClusterId: "do-sd-ciudad-colonial",
          priority: 87,
          familyFit: 80,
          typicalDurationMinutes: 180,
          bookingAdvice: "Controleer actuele openingsdagen; musea kunnen op maandag of feestdagen afwijkend werken.",
        }),
        highlight({
          id: "sd-dominican-food-route",
          title: "Dominicaanse smaken tussen markt en tafel",
          shortDescription: "Bouw één eetroute rond cacao, koffie, frituras en een eigentijdse interpretatie van de lokale keuken.",
          kind: "FOOD",
          interestIds: ["food", "culture", "history", "family-activities"],
          destinationClusterId: "do-sd-ciudad-colonial",
          priority: 89,
          familyFit: 90,
          typicalDurationMinutes: 210,
        }),
        highlight({
          id: "sd-malecon-evening",
          title: "Malecón bij dalende temperatuur",
          shortDescription: "Gebruik de zeeboulevard als venster op stadsleven, muziek en het contrast tussen oude stad en moderne hoofdstad.",
          kind: "CULTURE",
          interestIds: ["culture", "food", "nightlife", "photography"],
          destinationClusterId: "do-sd-gazcue-malecon",
          priority: 83,
          familyFit: 76,
          typicalDurationMinutes: 150,
        }),
        highlight({
          id: "sd-botanical-garden",
          title: "Botanische tuin als groene stadsdag",
          shortDescription: "Een ruim tegenwicht voor steen en verkeer, met tropische flora en genoeg ruimte voor een rustig gezinsmoment.",
          kind: "NATURE",
          interestIds: ["nature", "family-activities", "photography", "wellness"],
          destinationClusterId: "do-sd-modern-center",
          priority: 78,
          familyFit: 92,
          typicalDurationMinutes: 210,
        }),
      ],
    },
    {
      id: "do-samana",
      countryId: "do",
      name: "Samaná / Las Terrenas",
      slug: "samana",
      aliases: ["Samaná", "Las Terrenas", "Las Galeras", "Santa Bárbara de Samaná"],
      coverageLevel: "FLAGSHIP",
      center: { latitude: 19.205, longitude: -69.336 },
      shortDescription: "Een groen schiereiland waar walvissen, baaien, mangrove, watervallen en dorpen elk om hun eigen ideale dag vragen.",
      context: {
        headline: "Laat zee en microklimaat de volgorde bepalen",
        identity: "Samaná-stad is de toegang tot baai en walvissen, Las Terrenas combineert strand en eten, en Las Galeras voelt afgelegener en natuurgerichter.",
        bestFor: ["wildlife", "natuur", "stranden", "bootdagen", "langzaam reizen"],
        gettingAround: "De bergrug maakt korte hemelsbrede afstanden traag; combineer activiteiten per kustzijde en vermijd heen-en-weer rijden.",
        seasonalNote: "Bultrugwalvissen zijn de grote winterkans. Lokale regen kan sterk verschillen; bootdagen hangen meer van wind en zeegang af dan van een regenicoon.",
        localEtiquette: "Kies voor wildlife-aanbieders die afstandsregels respecteren en zie vissersdorpen als leefomgeving, niet als decor.",
      },
      previewHighlights: [
        highlight({
          id: "samana-whales",
          title: "Bultrugwalvissen in de Baai van Samaná",
          shortDescription: "Een uitgesproken seizoenskans waarbij de rustigste geschikte zeedag binnen je verblijf belangrijker is dan vroeg een vaste dag kiezen.",
          kind: "SIGNATURE",
          interestIds: ["wildlife", "nature", "water-activities", "family-activities", "photography"],
          destinationClusterId: "do-samana-town",
          priority: 100,
          familyFit: 82,
          minimumAge: 4,
          typicalDurationMinutes: 300,
          bookingAdvice: "Boek een vergunde aanbieder, controleer annuleringsbeleid en houd ruimte om naar een rustigere dag te schuiven.",
          seasonWindows: [
            { startMonth: 1, startDay: 15, endMonth: 3, endDay: 31, status: "PEAK", reason: "Kernperiode voor bultrugwalvissen in de baai." },
            { startMonth: 1, startDay: 1, endMonth: 4, endDay: 15, status: "AVAILABLE", reason: "Seizoensranden; aanwezigheid en officiële vaartperiode verifiëren." },
          ],
        }),
        highlight({
          id: "samana-los-haitises",
          title: "Los Haitises met kleine boot en gids",
          shortDescription: "Mangrove, kalksteeneilanden en grotten worden sterker wanneer ecologie en Taíno-context samen worden verteld.",
          kind: "NATURE",
          interestIds: ["nature", "history", "wildlife", "water-activities", "photography"],
          destinationClusterId: "do-samana-town",
          priority: 96,
          familyFit: 78,
          minimumAge: 5,
          typicalDurationMinutes: 420,
          bookingAdvice: "Vraag naar boottype, groepsgrootte, gidsinhoud en vertrekpunt; wind kan de route beïnvloeden.",
        }),
        highlight({
          id: "samana-el-limon",
          title: "El Limón na een droge aanloop",
          shortDescription: "De waterval is indrukwekkend, maar padconditie, schoeisel en vervoerskeuze bepalen of de ervaring ook met een kind goed werkt.",
          kind: "ACTIVE",
          interestIds: ["nature", "adventure", "family-activities", "photography"],
          destinationClusterId: "do-samana-el-limon",
          priority: 92,
          familyFit: 66,
          minimumAge: 6,
          typicalDurationMinutes: 300,
          seasonWindows: [
            { startMonth: 5, endMonth: 11, status: "LIMITED", reason: "Meer kans op modder en gladde paden; beoordeel recente regen lokaal." },
            ...yearRound("Jaarrond mogelijk; padconditie verschilt sterk na regen."),
          ],
        }),
        highlight({
          id: "samana-coson-bonita",
          title: "Kies de juiste strandkust voor de dag",
          shortDescription: "Playa Cosón, Bonita en de baaien bij Las Galeras verschillen in branding, reistijd en voorzieningen; kies op gezelschap en wind.",
          kind: "BEACH",
          interestIds: ["beach", "family-activities", "photography", "wellness"],
          destinationClusterId: "do-samana-las-terrenas",
          priority: 89,
          familyFit: 88,
          typicalDurationMinutes: 300,
        }),
        highlight({
          id: "samana-las-terrenas-food",
          title: "Las Terrenas: lokaal en internationaal aan één tafel",
          shortDescription: "De mix van Dominicaanse, vissers- en internationale keukens is deel van het plaatsverhaal, niet alleen een restaurantkeuze.",
          kind: "FOOD",
          interestIds: ["food", "culture", "nightlife", "family-activities"],
          destinationClusterId: "do-samana-las-terrenas",
          priority: 84,
          familyFit: 90,
          typicalDurationMinutes: 150,
        }),
        highlight({
          id: "samana-fronton-madama",
          title: "Afgelegen kust bij Las Galeras",
          shortDescription: "Playa Frontón en Madama bieden een avontuurlijker kustbeeld, maar vragen een betrouwbare lokale boot, kalme zee en goede timing.",
          kind: "ACTIVE",
          interestIds: ["adventure", "beach", "water-activities", "photography"],
          destinationClusterId: "do-samana-las-galeras",
          priority: 86,
          familyFit: 54,
          minimumAge: 10,
          typicalDurationMinutes: 360,
          bookingAdvice: "Alleen plannen met recente lokale zeestatus en een aanbieder met passende veiligheidsmiddelen.",
        }),
      ],
    },
    {
      id: "do-puerto-plata",
      countryId: "do",
      name: "Puerto Plata / Cabarete",
      slug: "puerto-plata",
      aliases: ["Puerto Plata", "Cabarete", "Sosúa"],
      coverageLevel: "STANDARD",
      center: { latitude: 19.766, longitude: -70.517 },
      shortDescription: "Noordkustmix van stadsgeschiedenis, actieve stranden, bergzicht en watervallen.",
      context: {
        headline: "Noordkust met twee snelheden",
        identity: "Puerto Plata geeft cultuur en stadscontext; Cabarete draait om wind, watersport en een informele strandcultuur.",
        bestFor: ["watersport", "avontuur", "geschiedenis", "actieve gezinnen"],
        gettingAround: "Plan Puerto Plata en Cabarete als aparte dagclusters; verkeer langs de kust kan reistijd onvoorspelbaar maken.",
        seasonalNote: "Cabarete profiteert van wind, maar beginners en gezinnen hebben baat bij het juiste dagdeel. Noordkustbuien zijn vaak lokaal.",
      },
      previewHighlights: [
        highlight({ id: "pop-27-charcos", title: "27 Charcos met passend circuit", shortDescription: "Kies het watervalcircuit op leeftijd, conditie en recente waterstand in plaats van automatisch de langste route.", kind: "ACTIVE", interestIds: ["adventure", "nature", "family-activities"], destinationClusterId: "do-pop-damajagua", priority: 93, familyFit: 70, minimumAge: 8, typicalDurationMinutes: 300 }),
        highlight({ id: "pop-historic-core", title: "Puerto Plata: fort, plein en victoriaanse stad", shortDescription: "Een compacte route verbindt Atlantische geschiedenis met de kleurrijke houten architectuur van het centrum.", kind: "CULTURE", interestIds: ["history", "culture", "photography", "food"], destinationClusterId: "do-pop-city", priority: 86, familyFit: 84, typicalDurationMinutes: 210 }),
        highlight({ id: "pop-cabarete-water", title: "Cabarete op windniveau", shortDescription: "Stem kitesurfen, windsurfen of een rustige stranddag af op ervaring, dagdeel en actuele wind.", kind: "ACTIVE", interestIds: ["water-activities", "adventure", "beach"], destinationClusterId: "do-pop-cabarete", priority: 91, familyFit: 62, minimumAge: 10, typicalDurationMinutes: 240 }),
        highlight({ id: "pop-isabel-torres", title: "Isabel de Torres bij helder zicht", shortDescription: "Berggroen en uitzicht boven Puerto Plata zijn het sterkst wanneer bewolking en operationele status meewerken.", kind: "NATURE", interestIds: ["nature", "photography", "family-activities"], destinationClusterId: "do-pop-city", priority: 79, familyFit: 88, typicalDurationMinutes: 180 }),
      ],
    },
    {
      id: "do-la-romana",
      countryId: "do",
      name: "La Romana / Bayahíbe",
      slug: "la-romana",
      aliases: ["La Romana", "Bayahíbe", "Dominicus", "Casa de Campo"],
      coverageLevel: "STANDARD",
      center: { latitude: 18.4273, longitude: -68.9728 },
      shortDescription: "Een zuidoostelijke uitvalsbasis voor rustig Caribisch water, Saona, duiken en cultuur langs de Río Chavón.",
      context: {
        headline: "Kustbasis met sterke dagtochten",
        identity: "Bayahíbe is compacter en maritiemer dan Punta Cana; La Romana voegt stad, industriegeschiedenis en Río Chavón toe.",
        bestFor: ["snorkelen", "duiken", "bootdagen", "gezinnen"],
        gettingAround: "Bayahíbe en La Romana zijn verschillende bases; controleer altijd vanuit welke haven of hotelzone een excursie vertrekt.",
        seasonalNote: "De Caribische zuidkust is vaak rustiger dan de Atlantische zijde, maar lokale wind en tropische systemen blijven bepalend.",
      },
      previewHighlights: [
        highlight({ id: "lr-saona", title: "Saona vanuit Bayahíbe", shortDescription: "Een kortere aanloop naar het nationale park maakt ruimte voor een kleinschaliger bootdag en meer natuuruitleg.", kind: "SIGNATURE", interestIds: ["beach", "nature", "water-activities", "family-activities"], destinationClusterId: "do-lr-bayahibe", priority: 95, familyFit: 86, minimumAge: 3, typicalDurationMinutes: 540 }),
        highlight({ id: "lr-catalina-diving", title: "Catalina voor snorkel of duikniveau", shortDescription: "Kies riflocatie en begeleiding op ervaring en zicht, niet alleen op een vaste pakketroute.", kind: "ACTIVE", interestIds: ["water-activities", "nature", "adventure"], destinationClusterId: "do-lr-city", priority: 86, familyFit: 65, minimumAge: 8, typicalDurationMinutes: 420 }),
        highlight({ id: "lr-altos-chavon", title: "Altos de Chavón met riviercontext", shortDescription: "Architectuur, kunst en uitzicht krijgen meer betekenis wanneer ook het omliggende landschap en de geënsceneerde oorsprong worden verteld.", kind: "CULTURE", interestIds: ["culture", "history", "shopping", "photography"], destinationClusterId: "do-lr-casa-de-campo", priority: 81, familyFit: 82, typicalDurationMinutes: 210 }),
        highlight({ id: "lr-bayahibe-village", title: "Bayahíbe tussen boten en dorpsleven", shortDescription: "Loop buiten de excursiepieken langs kust, lokale eetplekken en de maritieme geschiedenis van het dorp.", kind: "FOOD", interestIds: ["food", "culture", "beach", "photography"], destinationClusterId: "do-lr-bayahibe", priority: 78, familyFit: 90, typicalDurationMinutes: 150 }),
      ],
    },
    {
      id: "do-santiago",
      countryId: "do",
      name: "Santiago de los Caballeros",
      slug: "santiago",
      aliases: ["Santiago", "Cibao"],
      coverageLevel: "STANDARD",
      center: { latitude: 19.4517, longitude: -70.697 },
      shortDescription: "Het economische en culturele hart van de Cibao, sterk in muziek, tabak, kunst en stedelijk Dominicaans leven.",
      context: {
        headline: "Een stad voor wie het land wil begrijpen",
        identity: "Santiago voelt minder toeristisch en laat zien hoe Cibao-identiteit, industrie, honkbal, muziek en familiecultuur samenkomen.",
        bestFor: ["cultuur", "eten", "muziek", "lokale geschiedenis"],
        gettingAround: "Bezienswaardigheden liggen verspreid; groepeer centrum, Centro León en eventuele tabaksbezoeken per stadszijde.",
        seasonalNote: "Jaarrond geschikt voor stadsdagen; combineer buitenmomenten met gekoelde binnenlocaties in warme middagen.",
      },
      previewHighlights: [
        highlight({ id: "sti-centro-leon", title: "Centro León als culturele sleutel", shortDescription: "Kunst, antropologie en muziek geven een sterke basis voor alles wat je later in de Cibao ziet en hoort.", kind: "CULTURE", interestIds: ["culture", "history", "family-activities"], destinationClusterId: "do-sti-center", priority: 94, familyFit: 88, typicalDurationMinutes: 210 }),
        highlight({ id: "sti-tobacco", title: "Tabak als vakmanschap en economie", shortDescription: "Een zorgvuldig gekozen bezoek legt productie, arbeidsverhaal en wereldwijde reputatie naast elkaar.", kind: "CULTURE", interestIds: ["culture", "history", "shopping"], destinationClusterId: "do-sti-tamboril", priority: 83, familyFit: 48, minimumAge: 16, typicalDurationMinutes: 180 }),
        highlight({ id: "sti-monumento", title: "Monumento en stadspanorama", shortDescription: "Gebruik het monument niet alleen als fotostop, maar als ingang naar twintigste-eeuwse geschiedenis en stedelijke identiteit.", kind: "CULTURE", interestIds: ["history", "culture", "photography", "family-activities"], destinationClusterId: "do-sti-center", priority: 82, familyFit: 86, typicalDurationMinutes: 120 }),
        highlight({ id: "sti-cibao-food", title: "Cibao-keuken in de stad", shortDescription: "Zoek regionale gerechten en een lokale comedor voor een eetervaring die duidelijk verschilt van de resortkust.", kind: "FOOD", interestIds: ["food", "culture", "family-activities"], destinationClusterId: "do-sti-center", priority: 80, familyFit: 90, typicalDurationMinutes: 150 }),
      ],
    },
    {
      id: "do-central-mountains",
      countryId: "do",
      name: "Jarabacoa / Constanza",
      slug: "jarabacoa",
      aliases: ["Jarabacoa", "Constanza", "Cordillera Central"],
      coverageLevel: "STANDARD",
      center: { latitude: 19.1167, longitude: -70.6333 },
      shortDescription: "Koeler bergland met rivieren, landbouwvalleien, wandelroutes en een ander tempo dan de kust.",
      context: {
        headline: "De tropen op hoogte",
        identity: "Jarabacoa is de actieve rivier- en wandelbasis; Constanza draait om hoogland, landbouw en routes door de Cordillera Central.",
        bestFor: ["wandelen", "avontuur", "roadtrips", "koelere natuur"],
        gettingAround: "Bergwegen kosten tijd en weersomslag is lokaal; plan conservatieve rijtijden en vermijd onbekende routes in het donker.",
        seasonalNote: "Temperaturen zijn lager, vooral ’s avonds. Regen maakt wandelpaden en rivieractiviteiten snel technischer.",
      },
      previewHighlights: [
        highlight({ id: "mountains-rafting", title: "Rafting op waterstand en ervaring", shortDescription: "Een sterke Jarabacoa-dag wanneer recente regen, rivierstand en leeftijd passen bij de gekozen sectie.", kind: "ACTIVE", interestIds: ["adventure", "nature", "family-activities"], destinationClusterId: "do-mt-jarabacoa", priority: 91, familyFit: 62, minimumAge: 10, typicalDurationMinutes: 240 }),
        highlight({ id: "mountains-salto-jimenoa", title: "Salto de Jimenoa met padcheck", shortDescription: "Een toegankelijke bergnatuurervaring zolang bruggen, paden en recente regen vooraf zijn gecontroleerd.", kind: "NATURE", interestIds: ["nature", "photography", "family-activities"], destinationClusterId: "do-mt-jarabacoa", priority: 87, familyFit: 76, minimumAge: 6, typicalDurationMinutes: 180 }),
        highlight({ id: "mountains-constanza-route", title: "Constanza-landbouwroute", shortDescription: "Valleien, lokale producten en koeler klimaat vertellen waarom dit gebied agrarisch zo anders is dan de kust.", kind: "CULTURE", interestIds: ["road-trips", "food", "culture", "photography"], destinationClusterId: "do-mt-constanza", priority: 84, familyFit: 86, typicalDurationMinutes: 360 }),
        highlight({ id: "mountains-valle-nuevo", title: "Valle Nuevo met terreinplan", shortDescription: "Hooglandlandschap en stilte belonen voorbereiding op kou, wegconditie en beperkte voorzieningen.", kind: "NATURE", interestIds: ["nature", "adventure", "road-trips", "photography"], destinationClusterId: "do-mt-constanza", priority: 89, familyFit: 58, minimumAge: 8, typicalDurationMinutes: 480 }),
      ],
    },
    {
      id: "do-bahoruco",
      countryId: "do",
      name: "Barahona / Bahoruco",
      slug: "barahona",
      aliases: ["Barahona", "Bahoruco", "Lago Enriquillo"],
      coverageLevel: "BASIC",
      center: { latitude: 18.2085, longitude: -71.1008 },
      shortDescription: "Een ruiger zuidwesten van kustwegen, biosfeergebieden, larimar en sterke landschapscontrasten.",
      context: {
        headline: "Zuidwesten voor reizigers met tijd",
        identity: "Hier draait de reis om landschap, lokale gidsen en routes, niet om een dicht aanbod van kant-en-klare excursies.",
        bestFor: ["roadtrips", "natuur", "fotografie", "lokale context"],
        gettingAround: "Eigen vervoer of een ervaren chauffeur is vrijwel noodzakelijk; tank vroeg en bouw grote marges in.",
        seasonalNote: "Hitte is intens rond laaggelegen meren; berg- en kustmicroklimaten kunnen dezelfde dag sterk verschillen.",
      },
      previewHighlights: [
        highlight({ id: "bahoruco-coastal-road", title: "Kustroute Barahona–Paraíso", shortDescription: "Uitzicht, kiezelstranden en riviermondingen maken de rit zelf tot activiteit; stop alleen waar parkeren en branding veilig zijn.", kind: "SIGNATURE", interestIds: ["road-trips", "photography", "nature", "beach"], destinationClusterId: "do-bh-barahona", priority: 91, familyFit: 72, typicalDurationMinutes: 420 }),
        highlight({ id: "bahoruco-enriquillo", title: "Lago Enriquillo vroeg op de dag", shortDescription: "Een extreem laag en heet landschap met bijzondere ecologie, waarvoor actuele toegang en lokale begeleiding tellen.", kind: "NATURE", interestIds: ["nature", "wildlife", "photography", "road-trips"], destinationClusterId: "do-bh-enriquillo", priority: 88, familyFit: 55, minimumAge: 7, typicalDurationMinutes: 420 }),
        highlight({ id: "bahoruco-larimar", title: "Larimar met herkomstverhaal", shortDescription: "Leer hoe de steen wordt gewonnen en verwerkt en koop alleen waar herkomst en arbeidscontext transparant zijn.", kind: "CULTURE", interestIds: ["culture", "shopping", "history"], destinationClusterId: "do-bh-barahona", priority: 75, familyFit: 70, typicalDurationMinutes: 150 }),
      ],
    },
    {
      id: "do-pedernales",
      countryId: "do",
      name: "Pedernales",
      slug: "pedernales",
      aliases: ["Pedernales", "Bahía de las Águilas", "Jaragua"],
      coverageLevel: "BASIC",
      center: { latitude: 18.0384, longitude: -71.744 },
      shortDescription: "Afgelegen zuidwestkust met Bahía de las Águilas, droog bos en logistiek die voorbereiding beloont.",
      context: {
        headline: "Afgelegen natuur, geen spontane dagtrip",
        identity: "Pedernales is een grens- en natuurregio waar de kwaliteit van gids, vervoer en voorbereiding bepalender is dan luxe.",
        bestFor: ["afgelegen stranden", "natuur", "roadtrips", "fotografie"],
        gettingAround: "Afstanden zijn groot en dekking beperkt; bevestig brandstof, water, boot of 4x4 en terugkeertijd vooraf.",
        seasonalNote: "Droogte en hitte vragen veel water en zonbescherming; tropische verstoringen kunnen toegang snel veranderen.",
      },
      previewHighlights: [
        highlight({ id: "ped-bahia-aguilas", title: "Bahía de las Águilas met lichte voetafdruk", shortDescription: "Plan vervoer, schaduw, water en terugrit zo dat de beschermde kust ook werkelijk ongerept blijft.", kind: "SIGNATURE", interestIds: ["beach", "nature", "photography", "road-trips"], destinationClusterId: "do-ped-cabo-rojo", priority: 98, familyFit: 68, typicalDurationMinutes: 480 }),
        highlight({ id: "ped-jaragua", title: "Jaragua met lokale natuurgids", shortDescription: "Droog bos, lagunes en vogelwereld vragen terreinkennis en een route die past bij seizoen en toegangscondities.", kind: "NATURE", interestIds: ["nature", "wildlife", "photography", "adventure"], destinationClusterId: "do-ped-jaragua", priority: 90, familyFit: 54, minimumAge: 8, typicalDurationMinutes: 480 }),
        highlight({ id: "ped-border-context", title: "Grensregio met context", shortDescription: "Een zorgvuldig begeleid verhaal over handel, familiebanden en geschiedenis voorkomt dat de grens alleen een fotostop wordt.", kind: "CULTURE", interestIds: ["culture", "history", "road-trips"], destinationClusterId: "do-ped-town", priority: 72, familyFit: 66, typicalDurationMinutes: 150 }),
      ],
    },
    {
      id: "do-monte-cristi",
      countryId: "do",
      name: "Monte Cristi",
      slug: "monte-cristi",
      aliases: ["Montecristi", "El Morro"],
      coverageLevel: "BASIC",
      center: { latitude: 19.8483, longitude: -71.6459 },
      shortDescription: "Droge noordwestkust met mangrove, zout, maritieme geschiedenis en het markante El Morro.",
      context: {
        headline: "Droog, stil en maritiem",
        identity: "Monte Cristi contrasteert sterk met de groene noordkust en combineert kustecologie met handels- en onafhankelijkheidsgeschiedenis.",
        bestFor: ["vogels", "fotografie", "geschiedenis", "roadtrips"],
        gettingAround: "Voor mangrove en cayes is een lokale boot nodig; bevestig wind, schaduw en terugkomsttijd.",
        seasonalNote: "Hitte en wind bepalen het dagritme; start wandelingen en boottochten vroeg.",
      },
      previewHighlights: [
        highlight({ id: "mc-el-morro", title: "El Morro in zacht licht", shortDescription: "Het tafelbergprofiel, droge kustlandschap en baai zijn vroeg of laat op de dag op hun sterkst.", kind: "NATURE", interestIds: ["nature", "photography", "road-trips"], destinationClusterId: "do-mc-town", priority: 88, familyFit: 70, typicalDurationMinutes: 180 }),
        highlight({ id: "mc-mangrove", title: "Mangrove en cayes op rustige wind", shortDescription: "Een lokale bootroute toont kustecologie en vogels wanneer wind en zicht goed genoeg zijn.", kind: "NATURE", interestIds: ["wildlife", "nature", "water-activities", "photography"], destinationClusterId: "do-mc-town", priority: 84, familyFit: 64, minimumAge: 6, typicalDurationMinutes: 300 }),
        highlight({ id: "mc-history", title: "Monte Cristi en Máximo Gómez", shortDescription: "Historische huizen en het Manifest van Montecristi verbinden de stad met bredere Caribische onafhankelijkheidsbewegingen.", kind: "CULTURE", interestIds: ["history", "culture"], destinationClusterId: "do-mc-town", priority: 76, familyFit: 72, typicalDurationMinutes: 120 }),
      ],
    },
    {
      id: "do-juan-dolio",
      countryId: "do",
      name: "Boca Chica / Juan Dolio",
      slug: "juan-dolio",
      aliases: ["Boca Chica", "Juan Dolio", "Guayacanes"],
      coverageLevel: "BASIC",
      center: { latitude: 18.426, longitude: -69.433 },
      shortDescription: "Praktische zuidkust tussen luchthaven en hoofdstad, geschikt voor korte strandpauzes en lokale visadressen.",
      context: {
        headline: "Gebruik de kust bewust als tussenstop",
        identity: "Boca Chica is levendig en lokaal bezocht; Juan Dolio is langgerekter en rustiger, met andere strandcondities.",
        bestFor: ["korte stranddagen", "eten", "gezinnen", "stopovers"],
        gettingAround: "Kies één strandzone; verkeer richting Santo Domingo kan een korte afstand fors verlengen.",
        seasonalNote: "Jaarrond bruikbaar, maar weekenddrukte, waterkwaliteit en branding verschillen per locatie en dag.",
      },
      previewHighlights: [
        highlight({ id: "jd-boca-chica", title: "Boca Chica buiten de piekdrukte", shortDescription: "Ondiep water en lokaal strandritme werken het best op een rustig doordeweeks dagdeel.", kind: "BEACH", interestIds: ["beach", "culture", "family-activities", "food"], destinationClusterId: "do-jd-boca-chica", priority: 78, familyFit: 84, typicalDurationMinutes: 240 }),
        highlight({ id: "jd-juan-dolio", title: "Juan Dolio als landingsdag", shortDescription: "Een overzichtelijke strand- en eetcombinatie kan een aankomst- of vertrekdag waarde geven zonder ambitieus programma.", kind: "BEACH", interestIds: ["beach", "wellness", "food", "family-activities"], destinationClusterId: "do-jd-juan-dolio", priority: 80, familyFit: 90, typicalDurationMinutes: 240 }),
        highlight({ id: "jd-cueva-maravillas", title: "Cueva de las Maravillas onderweg", shortDescription: "Een begeleide grot vormt een inhoudelijke, relatief weerbestendige stop tussen Santo Domingo en La Romana.", kind: "CULTURE", interestIds: ["history", "nature", "family-activities", "road-trips"], destinationClusterId: "do-jd-east-route", priority: 83, familyFit: 86, typicalDurationMinutes: 150 }),
      ],
    },
    {
      id: "do-miches",
      countryId: "do",
      name: "Miches / Costa Esmeralda",
      slug: "miches",
      aliases: ["Miches", "Costa Esmeralda", "Montaña Redonda"],
      coverageLevel: "BASIC",
      center: { latitude: 18.9836, longitude: -69.0476 },
      shortDescription: "Een opkomende noordoostkust met lagunes, bergen en brede stranden tussen Punta Cana en Samaná.",
      context: {
        headline: "Opkomende kust met kwetsbare natuur",
        identity: "Miches combineert landbouw- en vissersgemeenschappen met nieuwe toeristische ontwikkeling en grote natuurgebieden.",
        bestFor: ["roadtrips", "natuur", "fotografie", "rustige kust"],
        gettingAround: "Attracties liggen verspreid; combineer per dag kust, berg of lagune en bevestig wegconditie.",
        seasonalNote: "Noordoostelijke buien en wind zijn lokaal; uitzichtpunten zijn alleen sterk bij voldoende zicht.",
      },
      previewHighlights: [
        highlight({ id: "miches-redonda", title: "Montaña Redonda bij helder zicht", shortDescription: "Het 360-gradenlandschap is de rit waard wanneer wolkenbasis en wegconditie goed zijn.", kind: "NATURE", interestIds: ["photography", "nature", "road-trips", "family-activities"], destinationClusterId: "do-miches-town", priority: 86, familyFit: 78, typicalDurationMinutes: 180 }),
        highlight({ id: "miches-limon-lagoon", title: "Laguna Limón met natuurgids", shortDescription: "Een wetlandsroute verbindt vogels, water en gemeenschapscontext zonder de plek te reduceren tot uitzichtpunt.", kind: "NATURE", interestIds: ["nature", "wildlife", "photography"], destinationClusterId: "do-miches-laguna", priority: 88, familyFit: 70, minimumAge: 6, typicalDurationMinutes: 300 }),
        highlight({ id: "miches-esmeralda", title: "Costa Esmeralda met eigen voorzieningen", shortDescription: "Een brede, vaak stille kust die voorbereiding op schaduw, eten, stroming en bereik vraagt.", kind: "BEACH", interestIds: ["beach", "nature", "wellness", "photography"], destinationClusterId: "do-miches-coast", priority: 82, familyFit: 68, typicalDurationMinutes: 300 }),
      ],
    },
    {
      id: "do-bani-azua",
      countryId: "do",
      name: "Baní / Azua",
      slug: "bani",
      aliases: ["Baní", "Azua", "Las Salinas", "Dunas de Baní"],
      coverageLevel: "BASIC",
      center: { latitude: 18.2796, longitude: -70.331 },
      shortDescription: "Zuidelijke roadtripcorridor met duinen, zoutpannen, landbouw en historische routes richting het zuidwesten.",
      context: {
        headline: "Maak van de doorreis een landschapsdag",
        identity: "Baní en Azua laten de overgang zien van hoofdstad naar droog zuidwesten, met landbouw, kust en geschiedenis.",
        bestFor: ["roadtrips", "landschap", "fotografie", "lokale producten"],
        gettingAround: "Stops liggen van de hoofdweg af; vertrek vroeg en vermijd zand- of kustpaden zonder lokale bevestiging.",
        seasonalNote: "Zon, wind en hitte zijn dominant; duinen zijn aangenamer vroeg en vragen veel water.",
      },
      previewHighlights: [
        highlight({ id: "bani-dunes", title: "Dunas de Baní vroeg op de dag", shortDescription: "Een zeldzaam Caribisch duinlandschap dat om koeler dagdeel, stevige schoenen en bescherming tegen zon en wind vraagt.", kind: "NATURE", interestIds: ["nature", "photography", "road-trips", "adventure"], destinationClusterId: "do-ba-las-calderas", priority: 91, familyFit: 62, minimumAge: 6, typicalDurationMinutes: 180 }),
        highlight({ id: "bani-mango", title: "Baní via landbouw en smaak", shortDescription: "Lokale producten en seizoensfruit geven de route inhoud, met mango als uitgesproken kans rond de oogstperiode.", kind: "FOOD", interestIds: ["food", "culture", "road-trips"], destinationClusterId: "do-ba-bani", priority: 76, familyFit: 88, typicalDurationMinutes: 120, seasonWindows: [{ startMonth: 5, endMonth: 8, status: "PEAK", reason: "Belangrijkste mangoperiode; exacte oogst verschilt per ras en jaar." }, ...yearRound("Lokale landbouwproducten zijn jaarrond onderdeel van de regio.")] }),
        highlight({ id: "azua-history", title: "Azua als historische routeplaats", shortDescription: "Een korte contextstop verbindt koloniale verplaatsingen, onafhankelijkheidsverhalen en de weg naar het zuidwesten.", kind: "CULTURE", interestIds: ["history", "culture", "road-trips"], destinationClusterId: "do-ba-azua", priority: 70, familyFit: 72, typicalDurationMinutes: 120 }),
      ],
    },
  ],
  destinationClusters: [
    { id: "do-pc-bavaro", countryId: "do", regionId: "do-punta-cana", name: "Bávaro", slug: "bavaro", aliases: ["El Cortecito", "Los Corales"], kind: "RESORT_AREA", center: { latitude: 18.6864, longitude: -68.4108 }, shortDescription: "Levendige kustzone met stranden, restaurants en veel excursie-ophaalpunten." },
    { id: "do-pc-cap-cana", countryId: "do", regionId: "do-punta-cana", name: "Cap Cana", slug: "cap-cana", aliases: ["Juanillo"], kind: "RESORT_AREA", center: { latitude: 18.504, longitude: -68.369 }, shortDescription: "Rustiger geplande kustzone met marina, Juanillo en natuurreservaat." },
    { id: "do-pc-macao", countryId: "do", regionId: "do-punta-cana", name: "Macao", slug: "macao", aliases: ["Playa Macao"], kind: "BEACH_AREA", center: { latitude: 18.7665, longitude: -68.5506 }, shortDescription: "Open Atlantisch strand en dorp ten noorden van Bávaro." },
    { id: "do-pc-uvero-alto", countryId: "do", regionId: "do-punta-cana", name: "Uvero Alto", slug: "uvero-alto", aliases: [], kind: "RESORT_AREA", center: { latitude: 18.806, longitude: -68.574 }, shortDescription: "Afgelegen resortstrook aan een dynamischere Atlantische kust." },
    { id: "do-pc-higuey", countryId: "do", regionId: "do-punta-cana", name: "Higüey", slug: "higuey", aliases: ["Salvaleón de Higüey"], kind: "TOWN", center: { latitude: 18.615, longitude: -68.707 }, shortDescription: "Regionale stad met basiliek, markten en dagelijks oostkustleven." },
    { id: "do-pc-bayahibe-gateway", countryId: "do", regionId: "do-punta-cana", name: "Cotubanamá-poort", slug: "cotubanama", aliases: ["Parque Nacional Cotubanamá"], kind: "NATURE_BASE", center: { latitude: 18.35, longitude: -68.71 }, shortDescription: "Westelijke natuur- en grotzone die doorgaans een volle excursiedag vraagt." },
    { id: "do-sd-ciudad-colonial", countryId: "do", regionId: "do-santo-domingo", name: "Ciudad Colonial", slug: "ciudad-colonial", aliases: ["Zona Colonial"], kind: "CITY_DISTRICT", center: { latitude: 18.473, longitude: -69.884 }, shortDescription: "Historisch centrum met monumenten, musea, pleinen en eten op loopafstand." },
    { id: "do-sd-gazcue-malecon", countryId: "do", regionId: "do-santo-domingo", name: "Gazcue / Malecón", slug: "gazcue-malecon", aliases: ["Malecón"], kind: "CITY_DISTRICT", center: { latitude: 18.465, longitude: -69.913 }, shortDescription: "Zeeboulevard en historische woonwijk tussen oud en modern centrum." },
    { id: "do-sd-modern-center", countryId: "do", regionId: "do-santo-domingo", name: "Modern Santo Domingo", slug: "modern-santo-domingo", aliases: ["Piantini", "Naco"], kind: "CITY_DISTRICT", center: { latitude: 18.477, longitude: -69.94 }, shortDescription: "Hedendaagse wijken voor gastronomie, winkels en culturele instellingen." },
    { id: "do-sd-east", countryId: "do", regionId: "do-santo-domingo", name: "Santo Domingo Este", slug: "santo-domingo-este", aliases: ["Los Tres Ojos"], kind: "CITY_DISTRICT", center: { latitude: 18.48, longitude: -69.84 }, shortDescription: "Oostzijde met kalksteengrotten en toegang tot de zuidkustroute." },
    { id: "do-samana-town", countryId: "do", regionId: "do-samana", name: "Santa Bárbara de Samaná", slug: "samana-stad", aliases: ["Samaná-stad"], kind: "TOWN", center: { latitude: 19.205, longitude: -69.336 }, shortDescription: "Baaihaven en toegangspunt voor walvissen en Los Haitises." },
    { id: "do-samana-las-terrenas", countryId: "do", regionId: "do-samana", name: "Las Terrenas", slug: "las-terrenas", aliases: [], kind: "BEACH_AREA", center: { latitude: 19.311, longitude: -69.543 }, shortDescription: "Strandplaats met sterke eetmix en meerdere kustzones." },
    { id: "do-samana-las-galeras", countryId: "do", regionId: "do-samana", name: "Las Galeras", slug: "las-galeras", aliases: [], kind: "NATURE_BASE", center: { latitude: 19.291, longitude: -69.197 }, shortDescription: "Rustige oostpunt voor afgelegen baaien en boottochten." },
    { id: "do-samana-el-limon", countryId: "do", regionId: "do-samana", name: "El Limón", slug: "el-limon", aliases: ["Salto El Limón"], kind: "NATURE_BASE", center: { latitude: 19.273, longitude: -69.448 }, shortDescription: "Landelijke watervalbasis tussen Samaná en Las Terrenas." },
    { id: "do-pop-city", countryId: "do", regionId: "do-puerto-plata", name: "Puerto Plata", slug: "puerto-plata-stad", aliases: [], kind: "TOWN", center: { latitude: 19.793, longitude: -70.688 }, shortDescription: "Historische noordkuststad onder Isabel de Torres." },
    { id: "do-pop-cabarete", countryId: "do", regionId: "do-puerto-plata", name: "Cabarete", slug: "cabarete", aliases: ["Kite Beach"], kind: "BEACH_AREA", center: { latitude: 19.759, longitude: -70.423 }, shortDescription: "Internationale watersportbasis met windgedreven dagritme." },
    { id: "do-pop-damajagua", countryId: "do", regionId: "do-puerto-plata", name: "Damajagua", slug: "damajagua", aliases: ["27 Charcos"], kind: "NATURE_BASE", center: { latitude: 19.733, longitude: -70.813 }, shortDescription: "Watervalcorridor voor begeleide actieve circuits." },
    { id: "do-lr-bayahibe", countryId: "do", regionId: "do-la-romana", name: "Bayahíbe / Dominicus", slug: "bayahibe", aliases: ["Dominicus"], kind: "BEACH_AREA", center: { latitude: 18.37, longitude: -68.84 }, shortDescription: "Compacte kustbasis voor Saona, snorkelen en duiken." },
    { id: "do-lr-city", countryId: "do", regionId: "do-la-romana", name: "La Romana", slug: "la-romana-stad", aliases: [], kind: "TOWN", center: { latitude: 18.427, longitude: -68.973 }, shortDescription: "Regionale stad en havenbasis bij Río Chavón." },
    { id: "do-lr-casa-de-campo", countryId: "do", regionId: "do-la-romana", name: "Casa de Campo / Río Chavón", slug: "casa-de-campo", aliases: ["Altos de Chavón"], kind: "RESORT_AREA", center: { latitude: 18.416, longitude: -68.891 }, shortDescription: "Geplande resortzone met kunstcomplex en rivieruitzicht." },
    { id: "do-sti-center", countryId: "do", regionId: "do-santiago", name: "Santiago centrum", slug: "santiago-centrum", aliases: ["Monumento"], kind: "CITY_DISTRICT", center: { latitude: 19.451, longitude: -70.697 }, shortDescription: "Stedelijke basis voor monument, cultuur, markten en eten." },
    { id: "do-sti-tamboril", countryId: "do", regionId: "do-santiago", name: "Tamboril", slug: "tamboril", aliases: [], kind: "TOWN", center: { latitude: 19.486, longitude: -70.612 }, shortDescription: "Tabaks- en maakindustriegebied buiten Santiago." },
    { id: "do-mt-jarabacoa", countryId: "do", regionId: "do-central-mountains", name: "Jarabacoa", slug: "jarabacoa", aliases: [], kind: "NATURE_BASE", center: { latitude: 19.116, longitude: -70.635 }, shortDescription: "Bergbasis voor rivieren, watervallen en actieve dagen." },
    { id: "do-mt-constanza", countryId: "do", regionId: "do-central-mountains", name: "Constanza", slug: "constanza", aliases: [], kind: "NATURE_BASE", center: { latitude: 18.91, longitude: -70.744 }, shortDescription: "Hooglandvallei voor landbouwroutes en Valle Nuevo." },
    { id: "do-bh-barahona", countryId: "do", regionId: "do-bahoruco", name: "Barahona / Paraíso", slug: "barahona-paraiso", aliases: ["San Rafael"], kind: "ROUTE_BASE", center: { latitude: 18.16, longitude: -71.12 }, shortDescription: "Basis voor de zuidwestelijke kustweg en larimargebied." },
    { id: "do-bh-enriquillo", countryId: "do", regionId: "do-bahoruco", name: "Lago Enriquillo", slug: "lago-enriquillo", aliases: ["La Descubierta"], kind: "NATURE_BASE", center: { latitude: 18.5, longitude: -71.6 }, shortDescription: "Heet laaglandmeer en biosfeergebied nabij de Haïtiaanse grens." },
    { id: "do-ped-town", countryId: "do", regionId: "do-pedernales", name: "Pedernales-stad", slug: "pedernales-stad", aliases: [], kind: "TOWN", center: { latitude: 18.038, longitude: -71.744 }, shortDescription: "Grensplaats en logistieke basis voor het uiterste zuidwesten." },
    { id: "do-ped-cabo-rojo", countryId: "do", regionId: "do-pedernales", name: "Cabo Rojo / Bahía de las Águilas", slug: "bahia-de-las-aguilas", aliases: ["Cabo Rojo"], kind: "BEACH_AREA", center: { latitude: 17.84, longitude: -71.64 }, shortDescription: "Afgelegen beschermde kust met beperkte voorzieningen." },
    { id: "do-ped-jaragua", countryId: "do", regionId: "do-pedernales", name: "Parque Nacional Jaragua", slug: "jaragua", aliases: ["Laguna Oviedo"], kind: "NATURE_BASE", center: { latitude: 17.83, longitude: -71.47 }, shortDescription: "Droog bos, lagunes en belangrijke vogelhabitats." },
    { id: "do-mc-town", countryId: "do", regionId: "do-monte-cristi", name: "Monte Cristi / El Morro", slug: "monte-cristi-stad", aliases: ["El Morro"], kind: "NATURE_BASE", center: { latitude: 19.85, longitude: -71.65 }, shortDescription: "Noordwestelijke kustbasis voor landschap, bootroutes en historie." },
    { id: "do-jd-boca-chica", countryId: "do", regionId: "do-juan-dolio", name: "Boca Chica", slug: "boca-chica", aliases: [], kind: "BEACH_AREA", center: { latitude: 18.453, longitude: -69.606 }, shortDescription: "Levendig, lokaal bezocht strand dicht bij luchthaven en hoofdstad." },
    { id: "do-jd-juan-dolio", countryId: "do", regionId: "do-juan-dolio", name: "Juan Dolio", slug: "juan-dolio", aliases: ["Guayacanes"], kind: "BEACH_AREA", center: { latitude: 18.426, longitude: -69.433 }, shortDescription: "Langgerekte zuidkust voor een rustige tussenstop." },
    { id: "do-jd-east-route", countryId: "do", regionId: "do-juan-dolio", name: "Oostelijke zuidkustroute", slug: "oostelijke-zuidkustroute", aliases: ["Cueva de las Maravillas"], kind: "ROUTE_BASE", center: { latitude: 18.45, longitude: -69.17 }, shortDescription: "Routecorridor tussen Santo Domingo en La Romana." },
    { id: "do-miches-town", countryId: "do", regionId: "do-miches", name: "Miches / Montaña Redonda", slug: "miches-stad", aliases: ["Montaña Redonda"], kind: "TOWN", center: { latitude: 18.983, longitude: -69.047 }, shortDescription: "Lokale basis voor berguitzicht en noordoostkust." },
    { id: "do-miches-laguna", countryId: "do", regionId: "do-miches", name: "Laguna Limón", slug: "laguna-limon", aliases: [], kind: "NATURE_BASE", center: { latitude: 19.057, longitude: -68.912 }, shortDescription: "Wetland- en vogelgebied achter de noordoostkust." },
    { id: "do-miches-coast", countryId: "do", regionId: "do-miches", name: "Costa Esmeralda", slug: "costa-esmeralda", aliases: ["Playa Esmeralda"], kind: "BEACH_AREA", center: { latitude: 19.099, longitude: -68.872 }, shortDescription: "Brede, weinig bebouwde kust met beperkte voorzieningen." },
    { id: "do-ba-bani", countryId: "do", regionId: "do-bani-azua", name: "Baní", slug: "bani-stad", aliases: [], kind: "TOWN", center: { latitude: 18.28, longitude: -70.332 }, shortDescription: "Landbouwstad en poort naar duinen en zuidwesten." },
    { id: "do-ba-las-calderas", countryId: "do", regionId: "do-bani-azua", name: "Las Calderas", slug: "las-calderas", aliases: ["Dunas de Baní", "Salinas"], kind: "NATURE_BASE", center: { latitude: 18.214, longitude: -70.53 }, shortDescription: "Duinen, zoutpannen en droge kustlandschappen." },
    { id: "do-ba-azua", countryId: "do", regionId: "do-bani-azua", name: "Azua", slug: "azua", aliases: [], kind: "TOWN", center: { latitude: 18.455, longitude: -70.735 }, shortDescription: "Historische en agrarische routeplaats richting Barahona." },
  ],
  nationalContext: {
    headline: "Eén land, opvallend veel microreizen",
    introduction: "De Dominicaanse Republiek is groter en gevarieerder dan een strandbestemming: Atlantische en Caribische kusten, oude stadswijken, bergvalleien, droog zuidwesten en regionale identiteiten vragen elk om een ander dagritme.",
    travelIdentity: "Afstanden, lokaal weer en wegconditie wegen zwaar. Een goede reis groepeert ervaringen per regio en bewaart flexibiliteit voor boot-, wandel- en wildlife-dagen.",
    culturalContext: [
      { id: "dr-culture-music", title: "Muziek is sociale infrastructuur", body: "Merengue en bachata horen niet alleen bij shows: ze leven in familiefeesten, cafés, colmados en publieke ruimte. Luisteren naar waar en voor wie muziek speelt geeft meer context dan alleen een dansles.", sourceIds: [SEED_SOURCE], dataStatus: "SEED" },
      { id: "dr-culture-food", title: "De hoofdmaaltijd vertelt de regio", body: "Rijst, bonen en gestoofd vlees vormen een bekende basis, maar kustvis, Cibao-producten, cacao, koffie, bakbanaan en lokale bereidingen verschillen per route. Vraag naar het gerecht van de dag.", sourceIds: [SEED_SOURCE], dataStatus: "SEED" },
      { id: "dr-culture-history", title: "Koloniale monumenten vragen meerdere perspectieven", body: "Santo Domingo bevat vroege Europese koloniale instituties in Amerika, maar het volledige verhaal omvat Taíno-erfgoed, slavernij, verzet, migratie en de vorming van de moderne Dominicaanse samenleving.", sourceIds: [SEED_SOURCE], dataStatus: "SEED" },
      { id: "dr-culture-everyday", title: "Warm contact, respectvolle voorbereiding", body: "Een begroeting en enkele woorden Spaans openen veel deuren. Vraag vóór foto’s, kleed je passend bij kerken en accepteer dat lokaal tempo en formele openingstijden niet altijd hetzelfde zijn.", sourceIds: [SEED_SOURCE], dataStatus: "SEED" },
    ],
    practicalFacts: [
      { id: "dr-fact-language", label: "Taal", value: "Spaans", note: "Buiten toeristische zones is basis-Spaans bijzonder nuttig." },
      { id: "dr-fact-currency", label: "Valuta", value: "Dominicaanse peso (DOP)", note: "Prijzen kunnen in toeristische zones ook in USD worden genoemd; controleer wisselkoers en betaalvaluta." },
      { id: "dr-fact-time", label: "Tijdzone", value: "Atlantic Standard Time (UTC−4)", note: "Er is doorgaans geen zomertijd." },
      { id: "dr-fact-distance", label: "Reistijd", value: "Plan op rijtijd, niet op kilometers", note: "Bergwegen, stadsverkeer en kustcorridors maken afstanden misleidend." },
      { id: "dr-fact-weather", label: "Weer", value: "Sterke regionale microklimaten", note: "Een landelijke weersverwachting is onvoldoende voor een boot-, berg- of strandbeslissing." },
    ],
    trustNote: "Deze Slice-1 context is expliciet gemarkeerde redactionele seeddata. Openingstijden, toegang, prijzen, weer, zeecondities en officiële adviezen moeten vóór gebruik live worden geverifieerd.",
  },
  sourceCoverage: {
    isSeedData: true,
    lastReviewedAt: "2026-07-12",
    confidence: 0.72,
    note: "Redactionele seeddata voor een volledig werkende preview. Niet gebruiken als live operationele bevestiging.",
    sources: [
      { id: SEED_SOURCE, name: "TripFit Dominican Republic editorial seed v1", type: "SEED_RESEARCH" },
      { id: "dr-tourism-official", name: "Ministerio de Turismo de República Dominicana", type: "OFFICIAL", url: "https://www.godominicanrepublic.com/" },
      { id: "unesco-santo-domingo", name: "UNESCO – Colonial City of Santo Domingo", type: "OFFICIAL", url: "https://whc.unesco.org/en/list/526/" },
    ],
  },
};
