-- Create a table for locations discovered or enriched by OpenClaw
CREATE TABLE IF NOT EXISTS location_metadata (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    place_name TEXT NOT NULL,
    province TEXT NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    character TEXT, -- coastal, inland, highland, urban
    discovery_reason TEXT,
    seo_content TEXT, -- Generated by Hermes
    last_seo_update TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(place_name, province)
);

-- Index for fast lookup by Hermes
CREATE INDEX IF NOT EXISTS idx_location_metadata_place ON location_metadata(place_name, province);
